package com.rezoxnemesis.videostudio;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;

/** Explicit image workspace; layered preview and learned synthesis are distinguished. */
public final class AnimateImageActivity extends Activity {
    private ProjectStore.Project project;private Spinner images,engine,fps,camera;private EditText prompt,duration,pack;private CheckBox lock;private SeekBar strength;private TextView result;private MotionBrush brush;private String jobId="";
    private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService decode=Executors.newSingleThreadExecutor();private int generation;
    private final ArrayList<ProjectStore.Asset> assets=new ArrayList<>();
    private final Runnable poll=new Runnable(){public void run(){try{JSONArray jobs=new JSONArray(getSharedPreferences("videostudio_native_v1",0).getString(ExecutionTruthPolicy.JOB_RECOVERY_PREF_KEY,"[]"));for(int i=0;i<jobs.length();i++){JSONObject job=jobs.getJSONObject(i);if(jobId.equals(job.optString("id")))result.setText(job.optString("state")+" · "+job.optInt("progress")+"%\n"+job.optString("detail"));}}catch(Exception ignored){}ui.postDelayed(this,500);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);project=new ProjectStore(this).get(getIntent().getStringExtra("projectId"));if(project==null){finish();return;}for(ProjectStore.Asset asset:project.assets)if(asset.mime.startsWith("image/"))assets.add(asset);if(assets.isEmpty()){Toast.makeText(this,"Import an image first",Toast.LENGTH_LONG).show();finish();return;}ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(20,14,20,20);scroll.addView(root);setContentView(scroll);
        root.addView(label("Animate Image",24));images=select(root,"Source image",assets.stream().map(a->a.name).toArray(String[]::new));brush=new MotionBrush();root.addView(brush,new LinearLayout.LayoutParams(-1,420));root.addView(label("Paint regions allowed to move. Unpainted regions stay fixed in learned synthesis. Clear removes the mask, allowing the whole image to change.",13));Button clear=button("Clear brush",()->{brush.strokes=new JSONArray();brush.invalidate();});root.addView(clear);
        images.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> parent){}public void onItemSelected(android.widget.AdapterView<?> parent,View view,int position,long id){load(position);}});
        String selected=getIntent().getStringExtra("assetId");for(int i=0;i<assets.size();i++)if(assets.get(i).id.equals(selected))images.setSelection(i);
        prompt=input(root,"Motion prompt","slow camera parallax, gentle head and clothing movement");engine=select(root,"Engine",new String[]{"Layered motion · bundled on-device","Learned frame synthesis · compatible model required"});pack=input(root,"Learned model pack ID","");duration=input(root,"Duration · 1–8 seconds","4");fps=select(root,"Frames per second",new String[]{"24","30"});camera=select(root,"Camera",new String[]{"locked","parallax","shake"});lock=new CheckBox(this);lock.setText("Anchor every generated frame to the reference image");lock.setChecked(true);root.addView(lock);root.addView(label("Style / motion strength",14));strength=new SeekBar(this);strength.setMax(100);strength.setProgress(50);root.addView(strength);
        root.addView(label("Layered motion moves existing portrait layers. It cannot invent blinks, speech, new limbs or unseen poses. Learned synthesis requires trained weights; none are bundled. Reference anchoring alone does not guarantee face identity.",14));
        result=label("Ready",14);root.addView(result);root.addView(button("Analyse Image Motion",()->send("analyse_image_motion")));root.addView(button("Generate Motion Plan",()->send("generate_motion_plan")));root.addView(button("Refine Motion Plan",()->send("refine_motion")));root.addView(button("Preview Layered Camera Motion",()->{if(engine.getSelectedItemPosition()!=0){result.setText("Learned preview needs a compatible model and generation. Use Animate + Render.");return;}brush.preview=!brush.preview;brush.start=SystemClock.uptimeMillis();brush.invalidate();result.setText("Analytic camera preview; subject pose synthesis is not shown here.");}));root.addView(button("Animate + Render MP4",()->send("animate_image")));root.addView(button("Cancel Generation",()->{if(!jobId.isEmpty())startService(new Intent(this,ControlService.class).setAction(ControlService.ACTION_LOCAL_CANCEL).putExtra("jobId",jobId));}));root.addView(button("Back to editor",this::finish));ui.post(poll);
    }
    private void load(int index){final int id=++generation;ProjectStore.Asset source=assets.get(index);decode.submit(()->{try{Bitmap bitmap=MediaThumbnail.load(this,source,1024);ui.post(()->{if(isDestroyed()||id!=generation){if(bitmap!=null)bitmap.recycle();return;}if(brush.image!=null)brush.image.recycle();brush.image=bitmap;brush.strokes=new JSONArray();brush.invalidate();});}catch(Exception e){ui.post(()->result.setText(e.getMessage()));}});}
    private void send(String operation){try{JSONObject request=new JSONObject().put("operation",operation).put("projectId",project.id).put("assetId",assets.get(images.getSelectedItemPosition()).id).put("prompt",prompt.getText().toString()).put("engine",engine.getSelectedItemPosition()==0?"layered":"learned").put("packId",pack.getText().toString().trim()).put("durationSeconds",Double.parseDouble(duration.getText().toString())).put("fps",Integer.parseInt(fps.getSelectedItem().toString())).put("camera",camera.getSelectedItem().toString()).put("subjectLock",lock.isChecked()).put("styleStrength",strength.getProgress()/100.0).put("motionStrokes",brush.strokes);
        result.setText("Preparing native operation…");ResultReceiver receiver=new ResultReceiver(ui){@Override protected void onReceiveResult(int code,Bundle bundle){try{JSONObject response=new JSONObject(bundle.getString("result","{}"));jobId=response.optString("jobId","");result.setText(response.toString(2));}catch(Exception e){result.setText(e.getMessage());}}};startForegroundService(new Intent(this,ControlService.class).setAction(ControlService.ACTION_LOCAL_MOTION).putExtra("parameters",request.toString()).putExtra("receiver",receiver));
    }catch(Exception e){result.setText(e.getMessage());}}
    private TextView label(String text,int size){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setPadding(0,10,0,6);return v;}
    private EditText input(LinearLayout root,String caption,String initial){root.addView(label(caption,14));EditText v=new EditText(this);v.setText(initial);root.addView(v);return v;}
    private Spinner select(LinearLayout root,String caption,String[] values){root.addView(label(caption,14));Spinner v=new Spinner(this);v.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));root.addView(v);return v;}
    private Button button(String caption,Runnable action){Button b=new Button(this);b.setText(caption);b.setOnClickListener(v->action.run());return b;}
    private final class MotionBrush extends View {
        Bitmap image;JSONArray strokes=new JSONArray();final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);RectF imageRect=new RectF();boolean preview;long start;
        MotionBrush(){super(AnimateImageActivity.this);setBackgroundColor(Color.BLACK);}
        @Override protected void onDraw(Canvas canvas){if(image==null)return;float scale=Math.min(getWidth()/(float)image.getWidth(),getHeight()/(float)image.getHeight());float w=image.getWidth()*scale,h=image.getHeight()*scale;imageRect.set((getWidth()-w)/2,(getHeight()-h)/2,(getWidth()+w)/2,(getHeight()+h)/2);canvas.save();if(preview){float phase=(SystemClock.uptimeMillis()-start)/1000f;canvas.translate((float)Math.sin(phase)*8,0);canvas.scale(1.02f,1.02f,getWidth()/2f,getHeight()/2f);postInvalidateOnAnimation();}canvas.drawBitmap(image,null,imageRect,null);paint.setColor(Color.argb(100,20,245,145));for(int i=0;i<strokes.length();i++){JSONObject s=strokes.optJSONObject(i);canvas.drawCircle(imageRect.left+(float)s.optDouble("x")*w,imageRect.top+(float)s.optDouble("y")*h,(float)s.optDouble("radius")*Math.min(w,h),paint);}canvas.restore();}
        @Override public boolean onTouchEvent(MotionEvent e){if(image==null)return true;if((e.getAction()==MotionEvent.ACTION_DOWN||e.getAction()==MotionEvent.ACTION_MOVE)&&imageRect.contains(e.getX(),e.getY())){getParent().requestDisallowInterceptTouchEvent(true);try{if(strokes.length()<128)strokes.put(new JSONObject().put("x",(e.getX()-imageRect.left)/imageRect.width()).put("y",(e.getY()-imageRect.top)/imageRect.height()).put("radius",.07));}catch(Exception ignored){}invalidate();}return true;}
    }
    @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);decode.shutdownNow();if(brush!=null){brush.preview=false;if(brush.image!=null)brush.image.recycle();}super.onDestroy();}
}
