package com.rezoxnemesis.videostudio;
import android.content.Context;import android.media.*;import android.net.Uri;import java.nio.*;

/** Bounded PCM RMS analysis of a clip's actual decoded audio; never draw a fabricated signal. */
final class AudioWaveform {
    static float[] extract(Context context,ProjectStore.Asset source,long inMs,long outMs)throws Exception{
        MediaExtractor extractor=new MediaExtractor();MediaCodec codec=null;
        try{extractor.setDataSource(context,Uri.parse(source.uri),null);MediaFormat format=null;for(int i=0;i<extractor.getTrackCount();i++){MediaFormat candidate=extractor.getTrackFormat(i);String mime=candidate.getString(MediaFormat.KEY_MIME);if(mime!=null&&mime.startsWith("audio/")){format=candidate;extractor.selectTrack(i);break;}}if(format==null)return null;
            long end=Math.min(outMs,inMs+120000);extractor.seekTo(inMs*1000,MediaExtractor.SEEK_TO_CLOSEST_SYNC);codec=MediaCodec.createDecoderByType(format.getString(MediaFormat.KEY_MIME));codec.configure(format,null,null,0);codec.start();boolean inputDone=false,outputDone=false;long deadline=android.os.SystemClock.elapsedRealtime()+15000;int channels=format.getInteger(MediaFormat.KEY_CHANNEL_COUNT),rate=format.getInteger(MediaFormat.KEY_SAMPLE_RATE),encoding=android.media.AudioFormat.ENCODING_PCM_16BIT;double[] energy=new double[128];long[] count=new long[128];MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();
            while(!outputDone){if(Thread.currentThread().isInterrupted())throw new InterruptedException();if(android.os.SystemClock.elapsedRealtime()>deadline)throw new java.io.IOException("Waveform analysis timed out");
                if(!inputDone){int index=codec.dequeueInputBuffer(1000);if(index>=0){ByteBuffer input=codec.getInputBuffer(index);int bytes=extractor.readSampleData(input,0);long pts=extractor.getSampleTime();if(bytes<0||pts>=end*1000){codec.queueInputBuffer(index,0,0,0,MediaCodec.BUFFER_FLAG_END_OF_STREAM);inputDone=true;}else{codec.queueInputBuffer(index,0,bytes,pts,0);extractor.advance();}}}
                int index=codec.dequeueOutputBuffer(info,1000);if(index==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED){MediaFormat decoded=codec.getOutputFormat();channels=decoded.getInteger(MediaFormat.KEY_CHANNEL_COUNT);rate=decoded.getInteger(MediaFormat.KEY_SAMPLE_RATE);if(decoded.containsKey(MediaFormat.KEY_PCM_ENCODING))encoding=decoded.getInteger(MediaFormat.KEY_PCM_ENCODING);if(encoding!=android.media.AudioFormat.ENCODING_PCM_16BIT&&encoding!=android.media.AudioFormat.ENCODING_PCM_FLOAT)throw new java.io.IOException("Unsupported waveform PCM format");}
                else if(index>=0){ByteBuffer output=codec.getOutputBuffer(index);if(output!=null&&info.size>0){output.position(info.offset);output.limit(info.offset+info.size);output.order(ByteOrder.LITTLE_ENDIAN);int sample=0,bytes=encoding==android.media.AudioFormat.ENCODING_PCM_FLOAT?4:2;while(output.remaining()>=bytes){double amplitude=bytes==4?output.getFloat():output.getShort()/32768.0;long time=info.presentationTimeUs/1000+sample/Math.max(1,channels)*1000L/rate;sample++;if(time<inMs||time>=end||!Double.isFinite(amplitude))continue;int bin=(int)Math.min(127,(time-inMs)*128/Math.max(1,end-inMs));energy[bin]+=amplitude*amplitude;count[bin]++;}}codec.releaseOutputBuffer(index,false);outputDone=(info.flags&MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;}}
            float[] result=new float[128];for(int i=0;i<128;i++)result[i]=count[i]==0?0:(float)Math.sqrt(energy[i]/count[i]);return result;
        }finally{if(codec!=null){try{codec.stop();}catch(Exception ignored){}codec.release();}extractor.release();}
    }
}
