package com.rezoxnemesis.videostudio;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

/** Human editor backed by the same SQLite project and native operations as MCP. */
public final class NativeEditorActivity extends Activity {
    private static final int PICK=4101;
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ExecutorService media=Executors.newSingleThreadExecutor();
    private final ExecutorService preview=Executors.newSingleThreadExecutor();
    private ProjectStore store;private ProjectStore.Project project;private ProjectStore.Clip selected;
    private EditorCompositionPreview composite;private boolean compositionMode;
    private LiveEditPlayer player;private FrameLayout canvas;private ImageView still;private TextView selectedLabel,status;private LinearLayout root;
    private EditorTimelineView timeline;private long playhead;private boolean playing;private int selectedGeneration;
    private Bitmap stillBitmap;private String replaceAsset="";private float zoom=64;private int binPage,uiEpoch;
    private static final Map<String,float[]> waveCache=new ConcurrentHashMap<>();
    private final Runnable refresh=new Runnable(){public void run(){if(isFinishing()||isDestroyed())return;ProjectStore.Project latest=store.get(project.id);if(latest!=null&&latest.updatedAt!=project.updatedAt){String id=selected==null?"":selected.id;project=latest;selected=find(id);build();}if(timeline!=null){if(compositionMode){playhead=composite.position();timeline.playheadMs=playhead;timeline.invalidate();}
                else if(playing&&selected!=null){long local=still.getVisibility()==View.VISIBLE?SystemClock.uptimeMillis()-imageStarted:Math.max(0,(long)((player.currentPositionMs()-selected.inMs)/selected.speed));timeline.playheadMs=clipStart(selected)+local;timeline.invalidate();}}ui.postDelayed(this,500);}};
    private long imageStarted;
    @Override public void onCreate(Bundle b){super.onCreate(b);store=new ProjectStore(this);project=store.get(getIntent().getStringExtra("projectId"));if(project==null)project=store.active();if(project==null)project=store.create("Untitled Project");player=new LiveEditPlayer(this);composite=new EditorCompositionPreview(this,message->Toast.makeText(this,"Preview: "+message,Toast.LENGTH_LONG).show());selected=project.clips.isEmpty()?null:project.clips.get(0);build();ui.post(refresh);}
    private ProjectStore.Clip find(String id){for(ProjectStore.Clip c:project.clips)if(c.id.equals(id))return c;return project.clips.isEmpty()?null:project.clips.get(0);}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);return c;}
    private TextView text(String value,int size){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(Color.WHITE);t.setPadding(dp(4),dp(6),dp(4),dp(6));return t;}
    private Button button(String label,Runnable run){Button b=new Button(this);b.setText(label);b.setTextSize(12);b.setOnClickListener(v->run.run());return b;}
    private void controls(String[] labels,Runnable[] actions){HorizontalScrollView scroll=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);for(int i=0;i<labels.length;i++)row.addView(button(labels[i],actions[i]));scroll.addView(row);root.addView(scroll);}
    private void build(){
        final int epoch=++uiEpoch;
        ScrollView scroll=new ScrollView(this);root=column();root.setPadding(dp(10),dp(8),dp(10),dp(20));root.setBackgroundColor(Color.rgb(5,8,18));scroll.addView(root);setContentView(scroll);
        root.addView(text(project.name+" · Editor",21));
        controls(new String[]{"Back","Import","Export","Animate Image","Storage","Approvals"},new Runnable[]{this::finish,this::pick,this::exportScreen,this::animateWorkspace,this::storageHub,()->startActivity(new Intent(this,AssistApprovalActivity.class))});
        canvas=new FrameLayout(this);canvas.setBackgroundColor(Color.BLACK);root.addView(canvas,new LinearLayout.LayoutParams(-1,dp(330)));player.attach(canvas);composite.attach(canvas);
        still=new ImageView(this);still.setScaleType(ImageView.ScaleType.FIT_CENTER);canvas.addView(still,new FrameLayout.LayoutParams(-1,-1));still.setVisibility(View.GONE);
        selectedLabel=text(selected==null?"Import or select media to begin":"Selected: "+project.asset(selected.assetId).name,14);root.addView(selectedLabel);
        controls(new String[]{"Play / Pause","Split","Undo","Redo","− Zoom","+ Zoom"},new Runnable[]{this::toggle,this::split,()->edit("undo",new JSONObject()),()->edit("redo",new JSONObject()),()->{zoom=Math.max(16,zoom/1.5f);timeline.zoom(zoom);},()->{zoom=Math.min(256,zoom*1.5f);timeline.zoom(zoom);}});
        SeekBar seek=new SeekBar(this);seek.setMax((int)Math.min(Integer.MAX_VALUE,project.outputDurationMs()));seek.setProgress((int)playhead);seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar b){playing=false;player.pause();composite.toggle(false);}public void onStopTrackingTouch(SeekBar b){seekTimeline(b.getProgress());}public void onProgressChanged(SeekBar b,int v,boolean user){if(user){playhead=v;timeline.playheadMs=v;timeline.invalidate();}}});root.addView(seek);
        HorizontalScrollView tracks=new HorizontalScrollView(this);timeline=new EditorTimelineView(this,project,new EditorTimelineView.Events(){public void select(ProjectStore.Clip c,long ms){selected=c;playhead=clipStart(c)+ms;showSelected(ms);timeline.selected=c.id;timeline.playheadMs=playhead;timeline.invalidate();}public void trim(ProjectStore.Clip c,long in,long out){selected=c;try{edit("trim",new JSONObject().put("inMs",in).put("outMs",out));}catch(Exception e){error(e);}}});timeline.zoom(zoom);timeline.selected=selected==null?"":selected.id;tracks.addView(timeline);root.addView(tracks);
        tracks.setOnDragListener((v,event)->{if(event.getAction()==DragEvent.ACTION_DRAG_STARTED)return event.getClipDescription()!=null&&event.getClipDescription().hasMimeType("text/plain");if(event.getAction()==DragEvent.ACTION_DROP){try{String id=event.getClipData().getItemAt(0).getText().toString();long start=Math.max(0,(long)((event.getX()+tracks.getScrollX()-60)/zoom*1000));int track=Math.max(0,Math.min(3,(int)((event.getY()-44)/52)));edit("add",new JSONObject().put("assetId",id).put("track",track).put("startMs",start));}catch(Exception e){error(e);}return true;}return true;});
        controls(new String[]{"Trim","Speed","Volume","Text","Crop","Colour","Mask","Transition","Track / Position","Keyframes","Duplicate","Move Left","Move Right","Remove"},new Runnable[]{this::trim,this::speed,this::volume,this::title,this::crop,this::colour,this::mask,this::transition,this::track,this::keyframes,()->edit("duplicate",new JSONObject()),()->move(-1),()->move(1),()->edit("remove",new JSONObject())});
        root.addView(text("Media Bin · tap to preview · hold to drag to timeline",17));
        HorizontalScrollView bin=new HorizontalScrollView(this);LinearLayout cards=new LinearLayout(this);bin.addView(cards);root.addView(bin);
        for(ProjectStore.Asset asset:project.assets.subList(Math.min(binPage*16,project.assets.size()),Math.min((binPage+1)*16,project.assets.size()))){LinearLayout card=column();card.setPadding(dp(6),dp(4),dp(6),dp(8));card.setBackgroundColor(Color.rgb(16,24,42));ImageView thumb=new ImageView(this);thumb.setScaleType(ImageView.ScaleType.FIT_CENTER);card.addView(thumb,new LinearLayout.LayoutParams(dp(140),dp(88)));card.addView(text(asset.name,12));card.addView(text(asset.generated?"Generated · "+asset.mime:asset.mime,11));card.setOnClickListener(v->previewAsset(asset));card.setOnLongClickListener(v->{card.startDragAndDrop(ClipData.newPlainText("asset",asset.id),new View.DragShadowBuilder(card),null,0);return true;});
            LinearLayout buttons=new LinearLayout(this);buttons.addView(button("Add",()->{try{edit("add",new JSONObject().put("assetId",asset.id).put("track",asset.mime.startsWith("audio/")?2:0).put("startMs",playhead));}catch(Exception e){error(e);}}));buttons.addView(button("⋮",()->assetMenu(asset)));card.addView(buttons);cards.addView(card,new LinearLayout.LayoutParams(dp(175),-2));
            media.submit(()->{if(epoch!=uiEpoch)return;try{Bitmap bitmap=MediaThumbnail.load(this,asset,192);ui.post(()->{if(!isDestroyed()&&thumb.isAttachedToWindow()){thumb.setImageBitmap(bitmap);timeline.thumbnail(asset.id,bitmap);}else if(bitmap!=null)bitmap.recycle();});}catch(Exception ignored){}});
        }
        int waveformCount=0;
        for(ProjectStore.Clip clip:project.clips){ProjectStore.Asset source=project.asset(clip.assetId);if(source==null||source.mime.startsWith("image/")||++waveformCount>8)continue;String key=source.id+":"+clip.inMs+":"+clip.outMs;float[] cached=waveCache.get(key);if(cached!=null){timeline.waveform(clip.id,cached);continue;}media.submit(()->{if(epoch!=uiEpoch)return;try{float[] data=AudioWaveform.extract(this,source,clip.inMs,clip.outMs);if(data!=null){if(waveCache.size()>128)waveCache.clear();waveCache.put(key,data);ui.post(()->{if(epoch==uiEpoch&&!isDestroyed())timeline.waveform(clip.id,data);});}}catch(Exception ignored){}});}
        controls(new String[]{"Previous media","Next media"},new Runnable[]{()->{binPage=Math.max(0,binPage-1);build();},()->{if((binPage+1)*16<project.assets.size())binPage++;build();}});
        status=text("Edits save immediately. ChatGPT changes appear here automatically.",12);root.addView(status);if(selected!=null)showSelected(Math.max(0,playhead-clipStart(selected)));
    }
    private long clipStart(ProjectStore.Clip clip){if(clip.track!=0)return clip.timelineStartMs;long start=0;for(ProjectStore.Clip c:project.clips){if(c==clip)return start;if(c.track==0)start+=c.outputDurationMs();}return start;}
    private void showSelected(long local){if(selected==null)return;ProjectStore.Asset asset=project.asset(selected.assetId);if(asset==null)return;selectedGeneration++;compositionMode=true;player.stop();player.setVisible(false);still.setVisibility(View.GONE);selectedLabel.setText("Selected: "+asset.name+" · "+String.format(Locale.US,"%.2fs / %.2fs",local/1000f,selected.outputDurationMs()/1000f));try{composite.show(project,clipStart(selected)+local,playing);}catch(Exception e){compositionMode=false;composite.hide();previewAsset(asset);error(e);}}
    private void previewAsset(ProjectStore.Asset asset){compositionMode=false;composite.hide();selectedGeneration++;final int generation=selectedGeneration;if(asset.mime.startsWith("image/")){player.pause();still.setVisibility(View.VISIBLE);player.setVisible(false);selectedLabel.setText("Loading "+asset.name+"…");preview.submit(()->{try{Bitmap bitmap=MediaThumbnail.load(this,asset,1024);ui.post(()->{if(generation!=selectedGeneration||isDestroyed()){if(bitmap!=null)bitmap.recycle();return;}still.setImageBitmap(bitmap);if(stillBitmap!=null)stillBitmap.recycle();stillBitmap=bitmap;selectedLabel.setText(asset.name+" · image");});}catch(Exception e){ui.post(()->error(e));}});}else if(asset.mime.startsWith("video/")||asset.mime.startsWith("audio/")){still.setVisibility(View.GONE);player.setVisible(true);player.play(Uri.parse(ProxyManager.previewUri(project,asset)),0,1,false);selectedLabel.setText(asset.name);}else{selectedLabel.setText("This file is a model/archive, not playable media");}}
    private void toggle(){if(selected==null)return;if(compositionMode){playing=!playing;composite.toggle(playing);return;}playing=!playing;if(!playing){player.pause();ui.removeCallbacks(imageBoundary);}else playCurrent();}
    private final Runnable imageBoundary=()->nextClip();
    private void playCurrent(){if(selected==null)return;showSelected(0);ProjectStore.Asset a=project.asset(selected.assetId);if(a.mime.startsWith("image/")){imageStarted=SystemClock.uptimeMillis();ui.removeCallbacks(imageBoundary);ui.postDelayed(imageBoundary,selected.outputDurationMs());}else player.playClip(Uri.parse(ProxyManager.previewUri(project,a)),selected.inMs,selected.outMs,selected.speed,this::nextClip);}
    private void nextClip(){if(!playing)return;int index=project.clips.indexOf(selected)+1;while(index<project.clips.size()&&project.clips.get(index).track!=0)index++;if(index>=project.clips.size()){playing=false;player.pause();return;}selected=project.clips.get(index);playhead=clipStart(selected);playCurrent();}
    private void seekTimeline(long at){long start=0;for(ProjectStore.Clip c:project.clips)if(c.track==0){if(at<start+c.outputDurationMs()){selected=c;playhead=at;showSelected(at-start);return;}start+=c.outputDurationMs();}}
    private void edit(String operation,JSONObject args){try{args.put("operation",operation);if(selected!=null)args.put("clipId",selected.id);args.put("expectedUpdatedAt",project.updatedAt);EditorCommands.execute(store,project.id,args);String id=selected==null?"":selected.id;project=store.get(project.id);selected=find(id);getSharedPreferences("videostudio_native_v1",0).edit().putLong("editor_project_changed",System.currentTimeMillis()).apply();startService(new Intent(this,ControlService.class).setAction(ControlService.ACTION_SYNC));build();}catch(Exception e){error(e);project=store.get(project.id);}}
    private void error(Exception e){Toast.makeText(this,e.getMessage()==null?"Action failed":e.getMessage(),Toast.LENGTH_LONG).show();}
    private void input(String label,String initial,java.util.function.Consumer<String> apply){EditText value=new EditText(this);value.setText(initial);new AlertDialog.Builder(this).setTitle(label).setView(value).setPositiveButton("Apply",(d,w)->{try{apply.accept(value.getText().toString());}catch(Exception e){error(e);}}).setNegativeButton("Cancel",null).show();}
    private void split(){if(selected==null)return;try{long local=compositionMode?Math.max(0,composite.position()-clipStart(selected)):still.getVisibility()==View.VISIBLE?Math.max(0,playhead-clipStart(selected)):Math.max(0,(long)((player.currentPositionMs()-selected.inMs)/selected.speed));edit("split",new JSONObject().put("atMs",selected.inMs+(long)(local*selected.speed)));}catch(Exception e){error(e);}}
    private void trim(){if(selected==null)return;input("Trim start,end in seconds",selected.inMs/1000f+","+selected.outMs/1000f,v->{try{String[] a=v.split(",");edit("trim",new JSONObject().put("inMs",(long)(Double.parseDouble(a[0])*1000)).put("outMs",(long)(Double.parseDouble(a[1])*1000)));}catch(Exception e){error(e);}});}
    private void speed(){if(selected==null)return;input("Playback speed · 0.25–4",String.valueOf(selected.speed),v->{try{edit("speed",new JSONObject().put("value",Double.parseDouble(v)));}catch(Exception e){error(e);}});}
    private void volume(){if(selected==null)return;input("Volume · 0 mute, 1 normal, 2 maximum",String.valueOf(selected.volume),v->{try{edit("volume",new JSONObject().put("value",Double.parseDouble(v)));}catch(Exception e){error(e);}});}
    private void title(){if(selected==null)return;input("Text overlay",selected.title,v->{try{edit("text",new JSONObject().put("text",v));}catch(Exception e){error(e);}});}
    private void crop(){if(selected==null)return;input("Crop left,top,right,bottom · 0–1","0,0,1,1",v->{try{String[] a=v.split(",");JSONArray bounds=new JSONArray();for(String n:a)bounds.put(Double.parseDouble(n));if(bounds.length()!=4)throw new IllegalArgumentException("Enter four bounds");edit("effects",new JSONObject().put("effects",new JSONObject().put("cropBounds",bounds)));}catch(Exception e){error(e);}});}
    private void colour(){String[] looks={"none","cinematic","teal_orange","warm_film","cool_night","noir","high_contrast"};new AlertDialog.Builder(this).setTitle("Colour effect").setItems(looks,(d,i)->{try{edit("effects",new JSONObject().put("effects",new JSONObject().put("colorPreset",looks[i])));}catch(Exception e){error(e);}}).show();}
    private void mask(){String[] values={"none","circle","rounded_rect","green_screen"};new AlertDialog.Builder(this).setTitle("Feathered alpha mask").setItems(values,(d,i)->{try{edit("effects",new JSONObject().put("effects",new JSONObject().put("mask",values[i]).put("maskFeather",.03)));}catch(Exception e){error(e);}}).show();}
    private void transition(){String[] values={"none","fade","slide_left","slide_right","zoom_in"};new AlertDialog.Builder(this).setTitle("Clip entry/exit motion").setItems(values,(d,i)->{try{edit("transition",new JSONObject().put("value",values[i]));}catch(Exception e){error(e);}}).show();}
    private void track(){if(selected==null)return;input("Track 0–3, start seconds",selected.track+","+selected.timelineStartMs/1000f,v->{try{String[] a=v.split(",");edit("track",new JSONObject().put("track",Integer.parseInt(a[0])).put("startMs",(long)(Double.parseDouble(a[1])*1000)));}catch(Exception e){error(e);}});}
    private void keyframes(){if(selected==null)return;input("End keyframe: x,y,scale,rotation","0,0,1,0",v->{try{String[] a=v.split(",");JSONObject end=new JSONObject().put("t",1).put("x",Double.parseDouble(a[0])).put("y",Double.parseDouble(a[1])).put("scale",Double.parseDouble(a[2])).put("rotation",Double.parseDouble(a[3]));JSONArray frames=new JSONArray().put(new JSONObject().put("t",0).put("scale",1)).put(end);edit("effects",new JSONObject().put("effects",new JSONObject().put("editorKeyframes",frames)));}catch(Exception e){error(e);}});}
    private void move(int delta){if(selected==null)return;try{edit("move",new JSONObject().put("index",project.clips.indexOf(selected)+delta));}catch(Exception e){error(e);}}
    private void assetMenu(ProjectStore.Asset asset){new AlertDialog.Builder(this).setTitle(asset.name).setItems(new String[]{"Preview","Rename","Replace with picked file","Remove from project"},(d,i)->{if(i==0)previewAsset(asset);if(i==1)input("Rename",asset.name,v->{try{edit("rename_asset",new JSONObject().put("assetId",asset.id).put("name",v));}catch(Exception e){error(e);}});if(i==2){replaceAsset=asset.id;pick();}if(i==3)new AlertDialog.Builder(this).setMessage("Remove from bin and timeline? The source file will be kept.").setPositiveButton("Remove",(dialog,w)->{try{edit("delete_asset",new JSONObject().put("assetId",asset.id));}catch(Exception e){error(e);}}).setNegativeButton("Cancel",null).show();}).show();}
    private void pick(){Intent picker=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*").putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","video/*","audio/*"}).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,replaceAsset.isEmpty());startActivityForResult(picker,PICK);}
    @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==PICK&&result==RESULT_OK&&data!=null){List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());String replacement=replaceAsset;replaceAsset="";media.submit(()->{try{String added="";for(Uri uri:uris){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}ProjectStore.Project fresh=store.get(project.id);ProjectStore.Asset a=store.importUri(fresh,uri,replacement.isEmpty());added=a.id;}final String id=added;ui.post(()->{project=store.get(project.id);if(!replacement.isEmpty())try{edit("replace_asset",new JSONObject().put("assetId",replacement).put("replacementAssetId",id));}catch(Exception e){error(e);}else{selected=project.clips.isEmpty()?null:project.clips.get(project.clips.size()-1);build();}});}catch(Exception e){ui.post(()->error(e));}});}}
    private void exportScreen(){startActivity(new Intent(this,ExportActivity.class).putExtra("projectId",project.id));}
    private void animateWorkspace(){startActivity(new Intent(this,AnimateImageActivity.class).putExtra("projectId",project.id).putExtra("assetId",selected==null?"":selected.assetId));}
    private void storageHub(){startActivity(new Intent(this,StorageHubActivity.class));}
    @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);media.shutdownNow();preview.shutdownNow();composite.release();player.release();if(stillBitmap!=null)stillBitmap.recycle();super.onDestroy();}
}
