package com.rezoxnemesis.videostudio;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.widget.*;import org.json.*;
/** Multiple explicitly authorised SAF folders, including cloud providers exposed by installed apps. */
public final class StorageHubActivity extends Activity {
    private SharedPreferences prefs;private JSONArray folders;
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("videostudio_native_v1",0);draw();}
    private void draw(){try{folders=new JSONArray(prefs.getString("storage_hub_folders","[]"));}catch(Exception e){folders=new JSONArray();}LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,16,24,16);setContentView(root);TextView title=new TextView(this);title.setText("Storage Hub");title.setTextSize(24);root.addView(title);TextView info=new TextView(this);info.setText("Authorise individual folders through Android Files. Google Drive, OneDrive, Dropbox or Box appear if their installed provider supports folder access. You can authorise multiple folders/accounts exposed there. This does not sign into providers that lack an Android document provider.");root.addView(info);Button add=new Button(this);add.setText("Authorise another folder");add.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),1));root.addView(add);
        for(int i=0;i<folders.length();i++){final int index=i;JSONObject folder=folders.optJSONObject(i);if(folder==null)continue;String uri=folder.optString("uri");Button select=new Button(this);select.setText((uri.equals(prefs.getString("drive_workspace_tree_uri",""))?"✓ ":"")+folder.optString("label",Uri.parse(uri).getAuthority()));select.setOnClickListener(v->{new DriveWorkspaceProvider(this).link(Uri.parse(uri));draw();});select.setOnLongClickListener(v->{new AlertDialog.Builder(this).setItems(new String[]{"Rename folder/account label","Remove authorisation"},(d,which)->{if(which==0){EditText label=new EditText(this);label.setText(folder.optString("label"));new AlertDialog.Builder(this).setView(label).setPositiveButton("Save",(dialog,w)->{try{folder.put("label",label.getText().toString());prefs.edit().putString("storage_hub_folders",folders.toString()).apply();draw();}catch(Exception ignored){}}).show();}else{JSONArray keep=new JSONArray();for(int n=0;n<folders.length();n++)if(n!=index)keep.put(folders.opt(n));prefs.edit().putString("storage_hub_folders",keep.toString()).apply();if(uri.equals(prefs.getString("drive_workspace_tree_uri","")))new DriveWorkspaceProvider(this).unlink();try{getContentResolver().releasePersistableUriPermission(Uri.parse(uri),Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);}catch(Exception ignored){}draw();}}).show();return true;});root.addView(select);}Button close=new Button(this);close.setText("Back");close.setOnClickListener(v->finish());root.addView(close);
    }
    @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==1&&result==RESULT_OK&&data!=null&&data.getData()!=null)try{Uri uri=data.getData();int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);getContentResolver().takePersistableUriPermission(uri,flags);boolean found=false;for(int i=0;i<folders.length();i++)if(uri.toString().equals(folders.getJSONObject(i).optString("uri")))found=true;if(!found)folders.put(new JSONObject().put("uri",uri.toString()).put("label",uri.getAuthority()));prefs.edit().putString("storage_hub_folders",folders.toString()).apply();new DriveWorkspaceProvider(this).link(uri);draw();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
}
