package com.rezoxnemesis.videostudio;
import android.content.Context;import android.net.Uri;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import java.util.*;import java.util.concurrent.*;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=33,manifest=Config.NONE)
public class EditorCommandsTest {
    private Context context(){return RuntimeEnvironment.getApplication();}
    private ProjectStore.Project image(ProjectStore store){ProjectStore.Project p=store.create("Editor test");store.registerImportedAsset(p.id,Uri.parse("file:///source.png"),"Source","image/png",3000);return store.get(p.id);}
    private JSONObject args(String operation,ProjectStore.Project p)throws Exception{return new JSONObject().put("operation",operation).put("clipId",p.clips.get(0).id).put("expectedUpdatedAt",p.updatedAt);}
    @Test public void staleHumanEditCannotOverwriteAutonomousImport()throws Exception{ProjectStore human=new ProjectStore(context()),agent=new ProjectStore(context());ProjectStore.Project stale=image(human);agent.registerImportedAsset(stale.id,Uri.parse("file:///agent.png"),"Agent output","image/png",3000);try{EditorCommands.execute(human,stale.id,args("speed",stale).put("value",2));fail("Stale edit must fail");}catch(IllegalStateException expected){}ProjectStore.Project fresh=human.get(stale.id);assertEquals(2,fresh.assets.size());assertEquals(2,fresh.clips.size());assertEquals(1,fresh.clips.get(0).speed,0);}
    @Test public void staleLegacySaveCannotEraseNewProjectState()throws Exception{ProjectStore a=new ProjectStore(context()),b=new ProjectStore(context());ProjectStore.Project stale=image(a);ProjectStore.Project latest=b.get(stale.id);latest.name="New title";b.save(latest);stale.name="Old title";try{a.save(stale);fail("Must reject stale save");}catch(IllegalStateException expected){}assertEquals("New title",a.get(stale.id).name);}
    @Test public void undoRedoPersistAndRetainMediaBin()throws Exception{ProjectStore store=new ProjectStore(context());ProjectStore.Project p=image(store);EditorCommands.execute(store,p.id,args("speed",p).put("value",2));ProjectStore.Project current=store.get(p.id);ProjectStore.Asset bin=new ProjectStore.Asset();bin.id=UUID.randomUUID().toString();bin.uri="file:///generated.png";bin.name="Generated";bin.mime="image/png";current.assets.add(bin);store.save(current);ProjectStore reopened=new ProjectStore(context());EditorCommands.execute(reopened,p.id,new JSONObject().put("operation","undo"));assertEquals(1,reopened.get(p.id).clips.get(0).speed,0);assertEquals(2,reopened.get(p.id).assets.size());EditorCommands.execute(reopened,p.id,new JSONObject().put("operation","redo"));assertEquals(2,reopened.get(p.id).clips.get(0).speed,0);assertEquals(2,reopened.get(p.id).assets.size());}
    @Test public void splitAndDuplicateHaveIndependentIdentities()throws Exception{ProjectStore store=new ProjectStore(context());ProjectStore.Project p=image(store);EditorCommands.execute(store,p.id,args("split",p).put("atMs",1200));p=store.get(p.id);assertEquals(2,p.clips.size());assertEquals(1200,p.clips.get(0).outMs);assertEquals(1200,p.clips.get(1).inMs);assertNotEquals(p.clips.get(0).id,p.clips.get(1).id);assertEquals(3000,p.outputDurationMs());}
    @Test public void assetDeletionDoesNotDeleteSourceAndUndoRejectsDanglingAsset()throws Exception{ProjectStore store=new ProjectStore(context());ProjectStore.Project p=image(store);EditorCommands.execute(store,p.id,new JSONObject().put("operation","delete_asset").put("assetId",p.assets.get(0).id));assertTrue(store.get(p.id).assets.isEmpty());assertTrue(store.get(p.id).clips.isEmpty());try{EditorCommands.execute(store,p.id,new JSONObject().put("operation","undo"));fail();}catch(IllegalStateException expected){}assertTrue(store.get(p.id).clips.isEmpty());}
    @Test public void failedMutationRollsBackHistoryAndTimeline()throws Exception{ProjectStore store=new ProjectStore(context());ProjectStore.Project p=image(store);try{EditorCommands.execute(store,p.id,args("speed",p).put("value",99));fail();}catch(IllegalArgumentException expected){}assertEquals(1,store.get(p.id).clips.get(0).speed,0);try{EditorCommands.execute(store,p.id,new JSONObject().put("operation","undo"));fail();}catch(IllegalStateException expected){}assertEquals(p.updatedAt,store.get(p.id).updatedAt);}
    @Test public void extraTrackDurationAndSourceBoundsAreRespected()throws Exception{ProjectStore store=new ProjectStore(context());ProjectStore.Project p=image(store);EditorCommands.execute(store,p.id,new JSONObject().put("operation","add").put("assetId",p.assets.get(0).id).put("track",1).put("startMs",5000));assertEquals(8000,store.get(p.id).outputDurationMs());assertEquals(5000,ProjectStore.Clip.fromJson(store.get(p.id).clips.get(1).toJson()).timelineStartMs);}
    @Test public void approvalBindsParametersAndIsSingleUse()throws Exception{AssistApprovalStore approvals=new AssistApprovalStore(context());JSONObject params=new JSONObject().put("projectId","test").put("value",2);String id=approvals.request("editor_edit",params);JSONObject retry=new JSONObject(params.toString()).put("_approvedRequestId",id);assertFalse(approvals.consume("editor_edit",retry));approvals.decide(id,true);assertFalse(approvals.consume("export_project",retry));assertFalse(approvals.consume("editor_edit",new JSONObject(retry.toString()).put("value",3)));assertTrue(approvals.consume("editor_edit",retry));assertFalse(approvals.consume("editor_edit",retry));}
    @Test public void queuedManualRendererPrecedesBackgroundRenderer()throws Exception{RenderGate gate=new RenderGate();gate.acquire(false);List<String> order=Collections.synchronizedList(new ArrayList<>());CountDownLatch done=new CountDownLatch(2);Thread background=new Thread(()->{try{gate.acquire(false);order.add("background");gate.release();}catch(InterruptedException e){Thread.currentThread().interrupt();}finally{done.countDown();}}),manual=new Thread(()->{try{gate.acquire(true);order.add("manual");gate.release();}catch(InterruptedException e){Thread.currentThread().interrupt();}finally{done.countDown();}});try{background.start();manual.start();long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(3);while(manual.getState()!=Thread.State.WAITING&&System.nanoTime()<deadline)Thread.yield();assertEquals(Thread.State.WAITING,manual.getState());gate.release();assertTrue(done.await(3,TimeUnit.SECONDS));assertEquals(Arrays.asList("manual","background"),order);}finally{background.interrupt();manual.interrupt();}}
}
