package com.rezoxnemesis.videostudio;
import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.RobolectricTestRunner;import org.robolectric.annotation.Config;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=33,manifest=Config.NONE)
public class ImageMotionPlanTest {
    @Test public void facialAnimationCannotBeClaimedByLayeredEngine()throws Exception{JSONObject plan=ImageMotionPlan.compile(new JSONObject().put("prompt","character blinks and recoils"));assertFalse(plan.getBoolean("trueFrameSynthesis"));assertTrue(plan.getJSONArray("requirements").toString().contains("learned_subject_blink"));assertTrue(plan.getJSONArray("requirements").toString().contains("learned_subject_recoil"));}
    @Test public void invalidNumbersCannotAllocateUnboundedFrameSequence()throws Exception{for(double seconds:new double[]{0,9,Double.POSITIVE_INFINITY})try{ImageMotionPlan.compile(new JSONObject().put("durationSeconds",seconds));fail();}catch(Exception expected){}try{ImageMotionPlan.compile(new JSONObject().put("fps",1000));fail();}catch(IllegalArgumentException expected){}}
    @Test public void brushPreservesPixelsOutsideSelectedRegion()throws Exception{JSONObject plan=ImageMotionPlan.compile(new JSONObject().put("motionStrokes",new JSONArray().put(new JSONObject().put("x",.5).put("y",.5).put("radius",.1))));float[] mask=NativeTemporalSynthesis.mask(plan,32);assertEquals(0,mask[0],0);assertEquals(1,mask[16*32+16],0);for(float value:mask)assertTrue(value>=0&&value<=1);}
    @Test public void temporalModelContractRejectsStaticImageAndFlowModels()throws Exception{assertFalse(NativeTemporalSynthesis.compatible(new JSONObject().put("backend","onnx-sd-turbo-v1")));assertFalse(NativeTemporalSynthesis.compatible(new JSONObject().put("backend","onnx-raft-v1")));JSONObject motion=new JSONObject().put("model","model.onnx").put("edge",256).put("stateChannels",16).put("normalization","rgb-minus-one-to-one");JSONObject model=new JSONObject().put("backend","onnx-image-to-video-v1").put("motion",motion).put("files",new JSONObject().put("model.onnx","a".repeat(64)));assertTrue(NativeTemporalSynthesis.compatible(model));String fingerprint=NativeModelContract.fingerprint(model);motion.put("edge",384);assertNotEquals(fingerprint,NativeModelContract.fingerprint(model));}
    @Test public void motionTimingIsDeterministicAndCameraMapped()throws Exception{JSONObject plan=ImageMotionPlan.compile(new JSONObject().put("engine","learned").put("camera","parallax").put("durationSeconds",4).put("fps",30));assertEquals(120,plan.getInt("frameCount"));assertArrayEquals(ImageMotionPlan.controls(plan,20),ImageMotionPlan.controls(plan,20),0);assertEquals(0,ImageMotionPlan.controls(plan,0)[0],0);assertEquals(1,ImageMotionPlan.controls(plan,119)[0],0);assertTrue(ImageMotionPlan.controls(plan,0)[11]>0);assertFalse(plan.getBoolean("semanticQualityVerified"));}
    @Test public void playableMediaRequiredForBothNewVideoOperations(){assertTrue(ExecutionTruthPolicy.requiresValidatedMediaOutput("animate_image"));assertTrue(ExecutionTruthPolicy.requiresValidatedMediaOutput("render_generated_video"));assertFalse(ExecutionTruthPolicy.requiresValidatedMediaOutput("generate_motion_plan"));}
}
